### ISSUE TITLE
Errors after updating the module

### ISSUE THREAD

**Issue by bgewehr** [Dirk-Peter-md/ioBroker.sprinklecontrol#30]
After updating the module I get errors in my log:

```
2021-10-31 11:17:42.118  - [32minfo[39m: host.buanet-iobroker1 instance system.adapter.sprinklecontrol.0 started with pid 29402
2021-10-31 11:17:44.519  - [32minfo[39m: sprinklecontrol.0 (29402) starting. Version 0.2.7 in /opt/iobroker/node_modules/iobroker.sprinklecontrol, node: v12.20.0, js-controller: 3.3.18
2021-10-31 11:17:47.659  - [31merror[39m: sprinklecontrol.0 (29402) uncaught exception: Cannot read property 'name' of undefined
2021-10-31 11:17:47.661  - [31merror[39m: sprinklecontrol.0 (29402) TypeError: Cannot read property 'name' of undefined
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:966:47)
    at processImmediate (internal/timers.js:463:21)
2021-10-31 11:17:47.662  - [31merror[39m: sprinklecontrol.0 (29402) Cannot read property 'name' of undefined
2021-10-31 11:17:47.674  - [32minfo[39m: sprinklecontrol.0 (29402) cleaned everything up...
2021-10-31 11:17:47.684  - [32minfo[39m: sprinklecontrol.0 (29402) terminating
2021-10-31 11:17:47.686  - [33mwarn[39m: sprinklecontrol.0 (29402) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-10-31 11:17:47.697  - [31merror[39m: sprinklecontrol.0 (29402) uncaught exception: Cannot read property 'name' of undefined
2021-10-31 11:17:47.698  - [31merror[39m: sprinklecontrol.0 (29402) TypeError: Cannot read property 'name' of undefined
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:966:47)
    at processImmediate (internal/timers.js:463:21)
2021-10-31 11:17:47.699  - [31merror[39m: sprinklecontrol.0 (29402) Cannot read property 'name' of undefined
2021-10-31 11:17:47.701  - [31merror[39m: sprinklecontrol.0 (29402) uncaught exception: Cannot read property 'name' of undefined
2021-10-31 11:17:47.702  - [31merror[39m: sprinklecontrol.0 (29402) TypeError: Cannot read property 'name' of undefined
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:966:47)
    at processImmediate (internal/timers.js:463:21)
2021-10-31 11:17:47.703  - [31merror[39m: sprinklecontrol.0 (29402) Cannot read property 'name' of undefined
2021-10-31 11:17:47.705  - [31merror[39m: sprinklecontrol.0 (29402) uncaught exception: Cannot read property 'name' of undefined
2021-10-31 11:17:47.706  - [31merror[39m: sprinklecontrol.0 (29402) TypeError: Cannot read property 'name' of undefined
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:966:47)
    at processImmediate (internal/timers.js:463:21)
2021-10-31 11:17:47.706  - [31merror[39m: sprinklecontrol.0 (29402) Cannot read property 'name' of undefined
2021-10-31 11:17:48.343  - [31merror[39m: host.buanet-iobroker1 instance system.adapter.sprinklecontrol.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-10-31 11:17:48.345  - [32minfo[39m: host.buanet-iobroker1 Restart adapter system.adapter.sprinklecontrol.0 because enabled
2021-10-31 11:17:48.345  - [33mwarn[39m: host.buanet-iobroker1 Do not restart adapter system.adapter.sprinklecontrol.0 because restart loop detected
```

![image](https://user-images.githubusercontent.com/4056277/139578300-79ec79e9-dbc0-4c24-8df9-452c3953a860.png)

What can I do?

**Comment by bgewehr** [comment]
<html>
<body>


sprinklecontrol.0 | 2021-10-31 11:38:20.656 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
sprinklecontrol.0 | 2021-10-31 11:38:20.655 | info | terminating
sprinklecontrol.0 | 2021-10-31 11:38:20.652 | info | cleaned everything up...
sprinklecontrol.0 | 2021-10-31 11:38:20.645 | error | Cannot read property 'name' of undefined
sprinklecontrol.0 | 2021-10-31 11:38:20.644 | error | TypeError: Cannot read property 'name' of undefined at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:966:47) at processImmediate (internal/timers.js:463:21)
sprinklecontrol.0 | 2021-10-31 11:38:20.644 | error | uncaught exception: Cannot read property 'name' of undefined
sprinklecontrol.0 | 2021-10-31 11:38:20.642 | error | Cannot read property 'name' of undefined
sprinklecontrol.0 | 2021-10-31 11:38:20.642 | error | TypeError: Cannot read property 'name' of undefined at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:966:47) at processImmediate (internal/timers.js:463:21)
sprinklecontrol.0 | 2021-10-31 11:38:20.641 | error | uncaught exception: Cannot read property 'name' of undefined
sprinklecontrol.0 | 2021-10-31 11:38:20.640 | error | Cannot read property 'name' of undefined
sprinklecontrol.0 | 2021-10-31 11:38:20.639 | error | TypeError: Cannot read property 'name' of undefined at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:966:47) at processImmediate (internal/timers.js:463:21)
sprinklecontrol.0 | 2021-10-31 11:38:20.639 | error | uncaught exception: Cannot read property 'name' of undefined
sprinklecontrol.0 | 2021-10-31 11:38:20.637 | error | Cannot read property 'name' of undefined
sprinklecontrol.0 | 2021-10-31 11:38:20.636 | error | TypeError: Cannot read property 'name' of undefined at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.sprinklecontrol/main.js:966:47) at processImmediate (internal/timers.js:463:21)
sprinklecontrol.0 | 2021-10-31 11:38:20.635 | error | uncaught exception: Cannot read property 'name' of undefined
sprinklecontrol.0 | 2021-10-31 11:38:20.492 | warn | This object will not be created in future versions. Please report this to the developer.
sprinklecontrol.0 | 2021-10-31 11:38:20.492 | warn | Object sprinklecontrol.0.sprinkle.frei.actualSoilMoisture is invalid: obj.type has to exist
sprinklecontrol.0 | 2021-10-31 11:38:20.491 | warn | This object will not be created in future versions. Please report this to the developer.
sprinklecontrol.0 | 2021-10-31 11:38:20.490 | warn | Object sprinklecontrol.0.sprinkle.Rasen.actualSoilMoisture is invalid: obj.type has to exist
sprinklecontrol.0 | 2021-10-31 11:38:20.489 | warn | This object will not be created in future versions. Please report this to the developer.
sprinklecontrol.0 | 2021-10-31 11:38:20.488 | warn | Object sprinklecontrol.0.sprinkle.Bambus_Garten.actualSoilMoisture is invalid: obj.type has to exist
sprinklecontrol.0 | 2021-10-31 11:38:20.487 | warn | This object will not be created in future versions. Please report this to the developer.
sprinklecontrol.0 | 2021-10-31 11:38:20.486 | warn | Object sprinklecontrol.0.sprinkle.Bambus_Terrasse.actualSoilMoisture is invalid: obj.type has to exist
sprinklecontrol.0 | 2021-10-31 11:38:19.944 | info | state sprinklecontrol.0.control.parallelOfMax changed: 0 : 1 (ack = true)
sprinklecontrol.0 | 2021-10-31 11:38:19.940 | info | state sprinklecontrol.0.control.restFlow changed: 2000 (2000 Grundwasser) (ack = true)


</body>
</html>

**Comment by bgewehr** [comment]
Wenn ich die Objekte *SoilMoisture lösche, läuft das Modul mit Fehlern:

<html>
<body>


sprinklecontrol.0 | 2021-10-31 11:59:42.546 | info | state sprinklecontrol.0.sprinkle.Rasen.runningTime changed: 00:00 (ack = true)
-- | -- | -- | --
sprinklecontrol.0 | 2021-10-31 11:59:42.524 | info | state sprinklecontrol.0.sprinkle.Bambus_Garten.runningTime changed: 00:00 (ack = true)
sprinklecontrol.0 | 2021-10-31 11:59:42.489 | warn | Object of state "sprinklecontrol.0.sprinkle.frei.actualSoilMoisture" is missing the required property "common.type"
sprinklecontrol.0 | 2021-10-31 11:59:42.488 | info | state sprinklecontrol.0.sprinkle.Bambus_Terrasse.runningTime changed: 00:00 (ack = true)
sprinklecontrol.0 | 2021-10-31 11:59:42.465 | warn | Object of state "sprinklecontrol.0.sprinkle.Rasen.actualSoilMoisture" is missing the required property "common.type"
sprinklecontrol.0 | 2021-10-31 11:59:42.462 | warn | Object of state "sprinklecontrol.0.sprinkle.Bambus_Garten.actualSoilMoisture" is missing the required property "common.type"
sprinklecontrol.0 | 2021-10-31 11:59:42.457 | warn | Object of state "sprinklecontrol.0.sprinkle.Bambus_Terrasse.actualSoilMoisture" is missing the required property "common.type"
sprinklecontrol.0 | 2021-10-31 11:59:41.191 | error | sprinkle.frei.actualSoilMoisture, getObject => err: undefined
sprinklecontrol.0 | 2021-10-31 11:59:41.191 | error | sprinkle.Rasen.actualSoilMoisture, getObject => err: undefined
sprinklecontrol.0 | 2021-10-31 11:59:41.190 | error | sprinkle.Bambus_Garten.actualSoilMoisture, getObject => err: undefined
sprinklecontrol.0 | 2021-10-31 11:59:41.189 | error | sprinkle.Bambus_Terrasse.actualSoilMoisture, getObject => err: undefined
sprinklecontrol.0 | 2021-10-31 11:59:41.188 | warn | This object will not be created in future versions. Please report this to the developer.
sprinklecontrol.0 | 2021-10-31 11:59:41.187 | warn | Object sprinklecontrol.0.sprinkle.frei.actualSoilMoisture is invalid: obj.type has to exist
sprinklecontrol.0 | 2021-10-31 11:59:41.186 | warn | This object will not be created in future versions. Please report this to the developer.
sprinklecontrol.0 | 2021-10-31 11:59:41.185 | warn | Object sprinklecontrol.0.sprinkle.Rasen.actualSoilMoisture is invalid: obj.type has to exist
sprinklecontrol.0 | 2021-10-31 11:59:41.183 | warn | This object will not be created in future versions. Please report this to the developer.
sprinklecontrol.0 | 2021-10-31 11:59:41.181 | warn | Object sprinklecontrol.0.sprinkle.Bambus_Garten.actualSoilMoisture is invalid: obj.type has to exist
sprinklecontrol.0 | 2021-10-31 11:59:41.174 | warn | This object will not be created in future versions. Please report this to the developer.
sprinklecontrol.0 | 2021-10-31 11:59:41.172 | warn | Object sprinklecontrol.0.sprinkle.Bambus_Terrasse.actualSoilMoisture is invalid: obj.type has to exist
sprinklecontrol.0 | 2021-10-31 11:59:40.026 | info | state sprinklecontrol.0.control.parallelOfMax changed: 0 : 1 (ack = true)
sprinklecontrol.0 | 2021-10-31 11:59:40.018 | info | state sprinklecontrol.0.control.restFlow changed: 2000 (2000 Grundwasser) (ack = true)
sprinklecontrol.0 | 2021-10-31 11:59:37.974 | info | #1.0 => Set ID: frei(3) hinzugefügt - {"startFixDay":null,"startDay":null,"enabled":false,"booster":false,"endIrrigation":true,"autoOn":true,"autoOnID":"sprinklecontrol.0.sprinkle.frei.autoOn","objectName":"frei","objectID":"sprinklecontrol.0.sprinkle.frei.runningTime","idState":"mqtt-client.1.Gartenwasser.in.35","updateStateTimerID":null,"sprinkleID":3,"wateringTime":20,"wateringAdd":200,"wateringInterval":0,"pipeFlow":700,"methodControlSM":"calculation","triggerSM":"","inGreenhouse":false,"analogZPct":null,"analogOHPct":null,"soilMoisture":{"val":4,"pct":50,"bool":null,"min":0.08,"maxIrrigation":8,"maxRain":10,"triggersIrrigation":4,"pctTriggerIrrigation":50}}
sprinklecontrol.0 | 2021-10-31 11:59:37.973 | info | #1.0 => Set ID: Rasen(2) hinzugefügt - {"startFixDay":null,"startDay":null,"enabled":true,"booster":false,"endIrrigation":false,"autoOn":true,"autoOnID":"sprinklecontrol.0.sprinkle.Rasen.autoOn","objectName":"Rasen","objectID":"sprinklecontrol.0.sprinkle.Rasen.runningTime","idState":"mqtt-client.1.Gartenwasser.in.33","updateStateTimerID":null,"sprinkleID":2,"wateringTime":15,"wateringAdd":200,"wateringInterval":0,"pipeFlow":570,"methodControlSM":"calculation","triggerSM":"","inGreenhouse":false,"analogZPct":null,"analogOHPct":null,"soilMoisture":{"val":7,"pct":50,"bool":null,"min":0.14,"maxIrrigation":14,"maxRain":19,"triggersIrrigation":11.2,"pctTriggerIrrigation":80}}
sprinklecontrol.0 | 2021-10-31 11:59:37.972 | info | #1.0 => Set ID: Bambus_Garten(1) hinzugefügt - {"startFixDay":null,"startDay":null,"enabled":true,"booster":false,"endIrrigation":true,"autoOn":true,"autoOnID":"sprinklecontrol.0.sprinkle.Bambus_Garten.autoOn","objectName":"Bambus_Garten","objectID":"sprinklecontrol.0.sprinkle.Bambus_Garten.runningTime","idState":"mqtt-client.1.Gartenwasser.in.31","updateStateTimerID":null,"sprinkleID":1,"wateringTime":15,"wateringAdd":200,"wateringInterval":600,"pipeFlow":400,"methodControlSM":"calculation","triggerSM":"","inGreenhouse":false,"analogZPct":null,"analogOHPct":null,"soilMoisture":{"val":5,"pct":50,"bool":null,"min":0.1,"maxIrrigation":10,"maxRain":15,"triggersIrrigation":9,"pctTriggerIrrigation":90}}
sprinklecontrol.0 | 2021-10-31 11:59:37.970 | info | #1.0 => Set ID: Bambus_Terrasse(0) hinzugefügt - {"startFixDay":null,"startDay":null,"enabled":true,"booster":false,"endIrrigation":true,"autoOn":true,"autoOnID":"sprinklecontrol.0.sprinkle.Bambus_Terrasse.autoOn","objectName":"Bambus_Terrasse","objectID":"sprinklecontrol.0.sprinkle.Bambus_Terrasse.runningTime","idState":"mqtt-client.1.Gartenwasser.in.29","updateStateTimerID":null,"sprinkleID":0,"wateringTime":10,"wateringAdd":200,"wateringInterval":0,"pipeFlow":250,"methodControlSM":"calculation","triggerSM":"","inGreenhouse":false,"analogZPct":null,"analogOHPct":null,"soilMoisture":{"val":5,"pct":50,"bool":null,"min":0.1,"maxIrrigation":10,"maxRain":15,"triggersIrrigation":9,"pctTriggerIrrigation":90}}
sprinklecontrol.0 | 2021-10-31 11:59:37.899 | info | starting. Version 0.2.7 in /opt/iobroker/node_modules/iobroker.sprinklecontrol, node: v12.20.0, js-controller: 3.3.18


</body>
</html>

**Comment by bgewehr** [comment]
OK - I had to manually set the method to calculation for my "old" valves. Now it works as designed. Could be a default if no value exists from an uploaded config...
